language: cpp

compiler:
  - gcc
  - clang

script:
 - xmllint -version
 - echo "<html></html>" | xmllint --c14n --format - && echo
 - ./waf configure build_release &&
       ./tests/vfmd-test/run_tests ./build/release/vfmd
           --dir="tests/vfmd-test/tests/*/*" --actual-fails

before_install:
 # xmllint required for running vfmd-test tests
 - sudo apt-get update -qq
 - sudo apt-get install -qq libxml2 libxml2-utils

cache:
 - apt # Use Travis cache for Ubuntu packages
