#ifndef VFMDCONSTANTS_H
#define VFMDCONSTANTS_H

class VfmdConstants {
public:

enum VfmdBlockElementType {
    UNDEFINED_BLOCK_ELEMENT,
    NULL_BLOCK_ELEMENT,
    REF_RESOLUTION_BLOCK_ELEMENT,
    SETEXT_HEADER_ELEMENT,
    CODE_BLOCK_ELEMENT,
    ATX_HEADER_ELEMENT,
    BLOCKQUOTE_ELEMENT,
    HORIZONTAL_RULE_ELEMENT,
    UNORDERED_LIST_ELEMENT,
    ORDERED_LIST_ELEMENT,
    PARAGRAPH_ELEMENT,
    USER_BLOCK_ELEMENT = 100,
    MAX_USER_BLOCK_ELEMENT = 255
};

enum VfmdSpanElementType {
    TEXTSPAN_ELEMENT,
    LINK_ELEMENT,
    EMPHASIS_ELEMENT,
    CODE_SPAN_ELEMENT,
    IMAGE_ELEMENT,
    AUTOMATIC_LINK_ELEMENT,
    AUTOMATIC_LINK_BRACKETED_ELEMENT,
    HTML_ELEMENT,
    USER_SPAN_ELEMENT = 100,
    MAX_USER_SPAN_ELEMENT = 255
};

enum VfmdOpeningSpanTagStackNodeType {
    UNDEFINED_STACK_NODE = -1,
    BASE_STACK_NODE = 0,
    LINK_STACK_NODE,
    ASTERISK_EMPHASIS_STACK_NODE,
    UNDERSCORE_EMPHASIS_STACK_NODE,
    RAW_HTML_STACK_NODE,
    USER_STACK_NODE = 100
};

};

#endif // VFMDCONSTANTS_H
